name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # If you have build steps (npm run build), add here
      # For plain HTML/JS no build step is needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./    # Root folder or ./docs if your files are there
